import { useState } from 'react'
import './App.css'

function App() {
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [formData, setFormData] = useState({
    gender: '',
    age: '',
    hemoglobin: '',
    rbc: '',
    mcv: '',
    mch: '',
    mchc: '',
    hematocrit: ''
  })

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.id]: e.target.value })
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    setLoading(true)

    try {
      const response = await fetch('/api/predict.py', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData)
      })

      if (!response.ok) throw new Error('Prediction request failed')

      const data = await response.json()
      setResult(data)
    } catch (err) {
      alert('Error connecting to AI backend: ' + err.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="app-container">
      <div className="background-glow" />

      <header>
        <h1>Anemia Prediction</h1>
        <p>AI Clinical Diagnostic System</p>
      </header>

      <main className="card">
        <form onSubmit={handleSubmit}>
          <div className="form-grid">
            <div className="input-block">
              <label htmlFor="gender">Gender</label>
              <select id="gender" value={formData.gender} onChange={handleChange} required>
                <option value="" disabled>Select gender</option>
                <option value="1">Male</option>
                <option value="0">Female</option>
              </select>
            </div>

            <div className="input-block">
              <label htmlFor="age">Age</label>
              <input type="number" id="age" value={formData.age} onChange={handleChange} placeholder="Years" required min="0" />
            </div>

            <div className="input-block">
              <label htmlFor="hemoglobin">Hemoglobin (g/dL)</label>
              <input type="number" id="hemoglobin" step="0.1" value={formData.hemoglobin} onChange={handleChange} placeholder="9.0 - 18.0" required />
            </div>

            <div className="input-block">
              <label htmlFor="rbc">RBC Count (10¹²/L)</label>
              <input type="number" id="rbc" step="0.1" value={formData.rbc} onChange={handleChange} placeholder="3.5 - 6.0" required />
            </div>

            <div className="input-block">
              <label htmlFor="mcv">MCV (fL)</label>
              <input type="number" id="mcv" step="0.1" value={formData.mcv} onChange={handleChange} placeholder="70 - 100" required />
            </div>

            <div className="input-block">
              <label htmlFor="mch">MCH (pg)</label>
              <input type="number" id="mch" step="0.1" value={formData.mch} onChange={handleChange} placeholder="25 - 35" required />
            </div>

            <div className="input-block">
              <label htmlFor="mchc">MCHC (g/dL)</label>
              <input type="number" id="mchc" step="0.1" value={formData.mchc} onChange={handleChange} placeholder="28 - 36" required />
            </div>

            <div className="input-block">
              <label htmlFor="hematocrit">Hematocrit (%)</label>
              <input type="number" id="hematocrit" step="0.1" value={formData.hematocrit} onChange={handleChange} placeholder="Optional" />
            </div>
          </div>

          <button type="submit" className="submit-btn" disabled={loading}>
            {loading ? <div className="loading-spinner" /> : 'Run AI Diagnostic'}
          </button>
        </form>
      </main>

      {result && (
        <div className="result-overlay">
          <div className="result-card">
            <div className={`status-icon ${result.Anemia === 'Yes' ? 'status-positive' : 'status-negative'}`}>
              {result.Anemia === 'Yes' ? '⚠️' : '✅'}
            </div>
            <h2>{result.Anemia === 'Yes' ? 'Anemia Detected' : 'No Anemia Found'}</h2>
            <p className="probability">Confidence Score: {result.Probability}</p>

            <div className="disclaimer-box">
              This result is generated by a machine learning model based on clinical datasets.
              It is for informational purposes only. Please consult a physician for official medical advice.
            </div>

            <button className="close-btn" onClick={() => setResult(null)}>
              Dismiss
            </button>
          </div>
        </div>
      )}

      <footer>
        <p>&copy; 2026 PrecisionHealth AI. Optimized for medical professionals.</p>
      </footer>
    </div>
  )
}

export default App
